let data = [
    {
        id: "product_key_001",
        category:"women",
        name:"AIRism Drape Short Sleeve T-Shirt",
        img:"/img/p-1",
        price:65.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. equat ornare feugiat.",
    },
    {
        id: "product_key_002",
        category:"women",
        name:"Oversized Half Sleeve T-Shirt (Wide Striped)",
        img:"/img/p-2.avif",
        price:45.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula.  consequat ornare feugiat.",
    },
    {
        id: "product_key_003",
        category:"men",
        name:"Only Check Trouser",
        img:"/img/p-3.avif",
        price:89.50,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae gula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_004",
        category:"women",
        name:"Extra Fine Merino Ribbed Mock Neck Half Sleeve Sweater",
        img:"/img/p-4.avif",
        price:58.79,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula.  ornare feugiat.",
    },
    {
        id: "product_key_005",
        category:"women",
        name:"Rayon Short Sleeve Blouse (Printed)",
        img:"/img/p-5.avif",
        price:68.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vigula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_006",
        category:"watch",
        name:"Vintage Inspired Classic",
        img:"/img/p-6.webp",
        price:45.25,
        title:"Nullar eget sem vitae eros pharetra itae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_007",
        category:"women",
        name:"Linen Blend Open Collar Short Sleeve Shirt",
        img:"/img/p-7.avif",
        price:150.65,
        title:"Nullar eget sem vitae eros pharetra viverra. Namligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_008",
        category:"women",
        name:"Mercerized Cotton A Line Short Sleeve Dress",
        img:"/img/p-8.avif",
        price:100.35,
        title:"Nullar eget sem vitae eros pharetra viverraluctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_009",
        category:"shoes",
        name:"Nike Dunk Low",
        img:"/img/p-9.jpeg",
        price:79.55,
        title:"Nullar eget sem vitae eros pharetra vww vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_010",
        category:"women",
        name:"Cotton Long Sleeve Long Shirt Dress (Solid)",
        img:"/img/p-10.avif",
        price:42.65,
        title:"Nullar eget sem vitae eros pharetra Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_011",
        category:"men",
        name:"AIRism Cotton Crew Neck Short Sleeve T-Shirt",
        img:"/img/p-11.avif",
        price:84.25,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris rnare feugiat.",
    },
    {
        id: "product_key_012",
        category:"watch",
        name:"Herschel SpunBer",
        img:"/img/p-12.webp",
        price:89.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_013",
        category:"women",
        name:"HEATTECH Ultra Warm Crew Neck Long Sleeve T-Shirt",
        img:"/img/p-13.avif",
        price:99.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus  consequat ornare feugiat.",
    },
    {
        id: "product_key_014",
        category:"women",
        name:"Linen Blend Open Collar Short Sleeve Shirt (Striped)",
        img:"/img/p-14.avif",
        price:45.00,
        title:"Nullar eget sem vitae eros pharetra vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_015",
        category:"watch",
        name:"Mini Silver Mesh Watch",
        img:"/img/p-15.webp",
        price:59.25,
        title:"Nullar eget sem vitae eros pharetra  Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_016",
        category:"women",
        name:"V Neck Short Sleeve Mini Dress (Printed)",
        img:"/img/p-16.avif",
        price:87.65,
        title:"Nullar eget sem vitae ero viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_017",
        category:"men",
        name:"Modal Cotton Open Collar Short Sleeve Shirt (Printed)t",
        img:"/img/p-17.avif",
        price:45.85,
        title:"Nullar eget sem vitae eros pharetra viverra. tae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_018",
        category:"men",
        name:"Modal Cotton Stand Collar Short Sleeve Shirt",
        img:"/img/p-18.avif",
        price:77.75,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_019",
        category:"men",
        name:"Stretch Fleece Mock Neck Long Sleeve T-Shirt",
        img:"/img/p-19.avif",
        price:180.35,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris cons feugiat.",
    },
    {
        id: "product_key_020",
        category:"men",
        name:"Oversized Half Sleeve T-Shirt (Regular Striped)",
        img:"/img/p-20.avif",
        price:399.5,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligul aequat ornare feugiat.",
    },
    {
        id: "product_key_021",
        category:"men",
        name:"AIRism Short Sleeve Polo Shirt (Regular Collar)",
        img:"/img/p-21.avif",
        price:55.25,
        title:"Nullar eget sem vitae eros  viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_022",
        category:"men",
        name:"Modal Cotton Open Collar Short Sleeve Shirt",
        img:"/img/p-22.avif",
        price:69.00,
        title:"Nullar eget sem vitae eros pharetra viverra. luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_023",
        category:"watch",
        name:"overtime watch",
        img:"/img/p-23.webp",
        price:145.35,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_024",
        category:"bag",
        name:"STUDIO GHIBLI Round Mini Shoulder Bag",
        img:"/img/p-24.avif",
        price:88.00,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
    {
        id: "product_key_025",
        category:"bag",
        name:"Functional Backpack",
        img:"/img/p-25.avif",
        price:74.99,
        title:"Nullar eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.",
    },
]


// console.log(data)